<a href="https://colab.research.google.com/github/prabuddhayogi/ai-with-python/blob/numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
x=np.array([4,5,6])
x

array([4, 5, 6])

In [5]:
x.size

3

In [6]:
x.ndim

1

In [7]:
x.shape

(3,)

In [10]:
y=np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
y=np.arange(5,10)
y

array([5, 6, 7, 8, 9])

In [13]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a.ndim

2

In [15]:
a.size

6

In [16]:
a.shape

(2, 3)

In [17]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
y=a.reshape(3,2)

In [19]:
y.ndim

2

In [20]:
y.shape

(3, 2)

In [22]:
c=np.random.random((2,3))
c

array([[0.04798394, 0.13822789, 0.68447611],
       [0.75907745, 0.80148693, 0.53514496]])

In [24]:
c=np.full((3,4),8)
c

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [25]:
d=np.zeros((5,6))
d

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a=a.reshape(-1)
a

array([1, 2, 3, 4, 5, 6])